### ISSUE TITLE
Can't define entities of the same name in different contexts

### ISSUE THREAD

**Issue by jameslovell** [reactific/riddl#116]
For example:
`domain Inventory is {
    context ProductInventory is {
        entity Product is {???}
    }
}
context Vendor is {
    entity Product is {???}
} `

will not validate. It fails with the following error:
`[error] Error: ImprovingApp.riddl(78:31): 'Product' is not uniquely defined.
Definitions are:
  Product (ImprovingApp.riddl(161:13))
  Product (ImprovingApp.riddl(136:9))`

**Comment by reid-spencer** [comment]
Confirmed, that is a bug.

**Comment by reid-spencer** [comment]
@jameslovell - This error:
> [error] Error: ImprovingApp.riddl(78:31): 'Product' is not uniquely defined. Definitions are: Product (ImprovingApp.riddl(161:13)) Product (ImprovingApp.riddl(136:9))
occurs when you use the name "Product" in a context when resolving that name to a specific definition is ambiguous. The context is lost in IMprovingApp.riddl now, so I can't verify.  But it would be good if you could track down the place where the symbol `Product` is USED, not where it is defined. You can disambiguate it with a prefix.  In this case, using either `ProductInventory.Product` or `Vendor.Product` would work.
