### ISSUE TITLE
Support Application Definitions

### ISSUE THREAD

**Issue by reid-spencer** [reactific/riddl#251]
RIDDL needs to support applications, which are the main targets for Stories. However, we want to keep the definition of applications very logical and concise. We are not interested in modelling the forms of interaction with humans, as important as that is, but just the logical results of those interactions: views and actions.  A view is something that the application puts out to the user (again, form not being important but information content is).  An action is something the user initiates to the app. Both can be modelled as message interactions. Views presenting messages to the user, actions submit messages to the application.

**Comment by AlexWeinstein92** [comment]
Seems like a `User` could just be a collection of specific `Action`s (call them `UserAction`s) that have access to specified `Views`. These `Action`s can only be sent to these `Views`, and can be of the form 'use [`View.field` or custom data] for `UserAction.parameter` according to specified `Condition`s'. We then define handlers for them in the `View` that transform the `UserAction` into a `GatewayContext` `Action`.

`View`s should also have `Action`s that initialize other `View`s to simulate navigation. It would also provide us with something like a Page, a stateless `View` that initializes child `View`s with ability to send `Action`s to `GatewayContext` and handle the data for the `View`. A `Button` would be a `View` without the data fields, and `Form`s could be created with reusable `FormInput` components. I don't really think we'd need much else.
