### ISSUE TITLE
Feature request: ids inherent to entities

### ISSUE THREAD

**Issue by AlexWeinstein92** [reactific/riddl#367]
The below code shows how I would like to reference an entity's ID without creating it in a record. This seems like a reasonable request since every entity will have an ID representing it and its location.

```
entity Foo {
  handler HandleCreateFoo {
    on command CreateFoo {
      example {
        then send event FooInfo(
          fooId = @Foo.id
        }
      }
   }      
}
```

Additionally it would be nice to be able to create a generic state for entities such that when a record is created the fields in the generic state and the record state are merged. However I don't know how necessary this would be, especially if the above issue were resolved. See below for an example of what I am thinking of. The term `base` is a stand-in for whatever term is deemed most appropriate by RIDDL developers.

```
entity Foo {
  base GenericFoo {
    bar: Bar
  }

  record SomeFoo {
    someBar: Bar
  }
  handler HandleFooCommands {
    on command GetFoo {
      example {
        then send event FooInfo(
          bar = @GenericFoo.bar,
          someBar = @SomeFoo.someBar
        }
      }
   }      
}
```

**Comment by reid-spencer** [comment]
Riddl no longer deals with values, generated or otherwise so this feature won't be added
