### ISSUE TITLE
Path Validation broken in 0.21.0

### ISSUE THREAD

**Issue by AlexWeinstein92** [reactific/riddl#375]
Path validation seems completely broken in 0.21.0. [This test run](https://github.com/reactific/riddl/actions/runs/4735243508/jobs/8405207774?pr=374#step:6:1662) should not be passing, particularly the `DooFoo example Success` and `OtherState` field `foo`. The test example is reproduced below.

```
domain Example is {
  context ExampleContext is {
    command DoFoo is {foo: Foo}
    type Foo is {
      bar: String
    }
    entity FooEntity is {
      record FooExampleState is {
        foo: Foo
      }
    state FooExample of FooExampleState is {
      handler HandleFoo is {
         on command DooFoo {
             example Success {
                then set FooExamplexxxx.garbage to !Foo(garbage = "garbage")
             }
         }
       }
    }
  }
}
  context OtherContext is {
    entity OtherEntity is {
      record OtherState is {
        foo: Examplexxxx.Foo
      }
    }
  }
}```

**Comment by reid-spencer** [comment]
The expected error messages are now generated in 0.23.0 and later

**Comment by reid-spencer** [comment]
The suggested syntax is no longer accepted after 0.24.0 and the test case for #375 which is similar to the reported input does not produce an error.
