### ISSUE TITLE
Using Record breaks validation (Scala error)

### ISSUE THREAD

**Issue by AlexWeinstein92** [reactific/riddl#406]
Given below code
```
domain Example is {
    context ExampleContext is {
	command ToBar is {}
	command ToFoo is {}
	  type Foo is {
	    bar: String
	   }
	   entity FooEntity is {
              record FooExampleState is {
	         foo: Foo
	      }
	      state FooExample of FooExampleState is {
	         handler HandleFoo is {
	            on command ToBar {
		       example ScalaFailure {
		          then morph entity FooEntity to state BarExampleState with !BarExampleState(bar = @FooExampleState.foo.bar)
                           }
		       }
	           }
	 }
          record BarExampleState is {
	         bar: String
	      }
	      state BarExample of BarExampleState is {
	         handler HandleFoo is {
	            on command ToFoo {
		       example Success {
		          then morph entity FooEntity to state FooExample with !FooExampleState(foo = !Foo(bar = @BarExampleState.bar))
		       }
	           } 
	        }
	 }
    }
  }
}
```
Note how in `ToBar.ScalaFailure` there is a reference to `state BarExampleState`. This should read `state BarExample` instead, similar to `ToFoo.Success` having `state FooExample`.

The associated error is:
`[severe] Severe: empty(1:1): java.lang.ClassCastException: class com.reactific.riddl.language.ast.Definitions$Type cannot be cast to class com.reactific.riddl.language.ast.Definitions$State (com.reactific.riddl.language.ast.Definitions$Type and com.reactific.riddl.language.ast.Definitions$State are in unnamed module of loader 'app')`

**Comment by reid-spencer** [comment]
This issue now has a test case to prove that the exception no longer occurs.
